name: sendrax
description: Easily log climbs and track progress indoors and out.

version: 0.3.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc:
  firebase_auth:
  firebase_storage:
  cloud_firestore:
  cached_network_image:
  charts_flutter:
  shared_preferences:
  image_picker:
  uuid:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
  ios: true