name: sendrax
description: Easily log climbs and track progress indoors and out.

version: 0.0.0+16

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc:
  firebase_auth:
  cloud_firestore:
  shared_preferences:
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
